controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
arm_controller:
  ros__parameters:
    joints:
    - shoulder_joint
    - z_joint
    - elbow_joint
    - wrist_joint
    command_interfaces:
    - position
    state_interfaces:
    - position
    - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      goal_time: 3.0
      stopped_velocity_tolerance: 0.03
      shoulder_joint:
        trajectory: 0.1
        goal: 0.02
      z_joint:
        trajectory: 0.02
        goal: 0.005
      elbow_joint:
        trajectory: 0.1
        goal: 0.02
      wrist_joint:
        trajectory: 0.1
        goal: 0.02
gripper_controller:
  ros__parameters:
    joints:
    - left_finger_joint
    - right_finger_joint
    command_interfaces:
    - position
    state_interfaces:
    - position
    - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.01
      left_finger_joint:
        trajectory: 0.005
        goal: 0.001
      right_finger_joint:
        trajectory: 0.005
        goal: 0.001
